### PR TITLE
[WIP] [#48] Added defensive code for DatabaseConnection drivers that don't support transactions

### LINKED ISSUE #48: Mongodb Transaction Error
i m using mongodb in my project. So when ı generate `php artisan scribe:generate`, i get this error:
mongodb_transaction
How can i solve this error ? Is there any setting to disable mongodb connection? or to override `startDbTransaction()` that is trait method ?

### PR DESCRIPTION
**Pull request by Smudge3806**
Some third-party database drivers don't support transactions *cough* Jenssegers *cough*. I'm sure there are probably some more out there.

Thought I'd throw this out there as a possible solution, and get guidance from maintainers before writing the relevant Unit tests. 

Potentially fixes #48 
> **Please read the [contribution guidelines](https://scribe.readthedocs.io/en/latest/contributing.html), especially the section on making a pull request, before creating a PR.** Otherwise, your PR may be turned down.

### CODE REVIEW

**Comment by shalvah** [comment]
That's a good fix. Of course, we'd need to emit a warning at the very least. But do we proceed? What happens if a dev is using a non-test db? And hope likely is that to happen? Or is it better to fail and have a CLI flag that allows use without transactions?

**Comment by Smudge3806** [comment]
@shalvah Wrapped it in a layer of configuration that is hopefully extendable to future issues regarding databases.

I also added warnings to both the `beginDbTransaction` and `endDbTransaction` methods that to remind the user of the problems associated with allowing database drivers that don't support transactions.

If this meets with your general approval, I will update the documentation

File: config/scribe.php [hunk 1]
```diff
@@ -331,4 +331,23 @@
...
+     * [Advanced usage] Customize how Scribe interacts with your databases.
+     */
+    'databases' => [
+        /**
+         * [Advanced usage] If you would like to enable the use of database drivers which don't support transactions
+         * set this value to true.
+         *
+         * NB: Changes made to your database during generatation WILL persist!
+         */
+        'allow_no_transactions' => false,
```
Comment (shalvah) [inline config/scribe.php:345]: I think `allow_no_transactions` is somewhat confusing. How about `use_without_transactions`?

Also, I'd rather we not nest this. We can also collapse these two configs into one. Something like:

```php
'run_without_database_transactions' => [
    ],
```

Then the user can add whatever connections they're okay with.

File: src/Extracting/Strategies/Strategy.php [hunk 2]
```diff
@@ -24,6 +24,16 @@ public function __construct(DocumentationConfig $config)
         $this->config = $config;
     }
 
+    /**
+     * Returns a copy of the documentation config
+     *
+     * @return DocumentationConfig
+     */
+    public function getConfig()
```
Comment (shalvah) [inline src/Extracting/Strategies/Strategy.php:32]: Curious, why did you add this method?

Also, it says it returns a copy of the config, but that isn't correct. It returns the same object.

File: src/Extracting/DatabaseTransactionHelpers.php [hunk 3]
```diff
@@ -30,9 +49,60 @@ private function endDbTransaction()
 
         foreach ($connections as $conn) {
             try {
-                app('db')->connection($conn)->rollBack();
+                tap(
```
Comment (shalvah) [inline src/Extracting/DatabaseTransactionHelpers.php:52]: Can we not use `tap()`? I understand its purpose, but I dislike it because it reads less clearly to me.

File: src/Extracting/DatabaseTransactionHelpers.php [hunk 4]
```diff
@@ -30,9 +49,60 @@ private function endDbTransaction()
...
+                    app('db')->connection($conn),
+                    function ($driver) use ($conn) {
+                        if (self::driverSupportsTransactions($driver)) {
+                            return $driver->rollBack();
+                        }
+
+                        c::warn("Database driver [{$conn}] does not support transactions!");
```
Comment (shalvah) [inline src/Extracting/DatabaseTransactionHelpers.php:59]: Terminology. We need to be consistent. Is it the connection or the driver that does not support transactions?🙂

File: config/scribe.php (hunk 1 above)
Comment (Smudge3806) [reply config/scribe.php:345]: `use_without_transactions` sounds to me like we are introducing a secondary flow where no transactions will be used period.. perhaps I am nitpicking?! I agree that `allow_no_transactions` is a little confusing but 💯  that `use_without_transactions` is any less. I'll canvas for some opinions today with my team.

In terms of the nesting, this was actually where my thoughts where going at 3 AM this morning. In lue of a better name I 'll work this with the current name.

File: src/Extracting/Strategies/Strategy.php (hunk 2 above)
Comment (Smudge3806) [reply src/Extracting/Strategies/Strategy.php:32]: Because `DatabaseTransactionsHelper` is a trait that could be applied anywhere, and not exclusively to a child class of the abstract `Strategy`, the trait can't guarantee there is access to a instance property `$config`. Personally I think this is potentially something the language could add, however the correct approach at the trait level, would be to add the requirement for a method that would return an instance of the Config. Such method does not currently exist, so hence the new method.

Whilst I could have used in in-built `config` method from Laravel/Lumen, I felt you might prefer it if I stick to instances of the `DocumentationConfig`.

File: src/Extracting/DatabaseTransactionHelpers.php (hunk 3 above)
Comment (Smudge3806) [reply src/Extracting/DatabaseTransactionHelpers.php:52]: Yeah, `tap()` and `with()` appear to be relatively marmite in the reception. Consider it swapped out.

File: src/Extracting/DatabaseTransactionHelpers.php (hunk 4 above)
Comment (Smudge3806) [reply src/Extracting/DatabaseTransactionHelpers.php:59]: Hmmm... Honestly, It could be both, from the little reading around the subject I have done, some connections/databases don't support transactions and, library dependant, some drivers don't support transactions. Seen as an in-process transaction support **could** be developed for those drivers where the connections don't support transactions, I felt it prudent to lay the "blame" at the driver level rather than at the connection.

In the case of `Jenssegers`. MongoDB supports transactions, however Jenssegers has yet to implement this feature. It may also be the case that a user is using an older version of a library when the latest version does indeed support transactions. If that where the case, but the database itself was out-of-date and didn't support transactions, then surely that would be for the driver to handle?

Thoughts?

Comment (Smudge3806) [reply src/Extracting/DatabaseTransactionHelpers.php:59]: Re-reading this, I think my logic is a bit squirrelly. Basically, I think there are a few things we need to consider:

1. Database supports transactions & driver does not (Most likely)
1. Database and driver do not support transactions (Not likely but possible)
1. Database does not support transactions but driver does (doesn't really affect us)

In terms of our messaging and terminology we have to decide where we lay the fault. As we connect to the database using a driver/adaptor/connector, I think it is prudent to place the fault at that level. 

Relating this to `Illuminate\Database`, the Transactions methods are added to the `Illuminate\Database\Connection` class via a Concern/trait. So the correct terminology in this case would be "Connection" however, if I know nothing about the inner workings of Laravel, would I consider "Connection" as the actual connection to the database server or the software responsible for initiating said connection?

In terms of design patterns, `Illuminate\Database` utilizes the Adaptor pattern for its various "Connection" classes. This would probably be the most correct terminology however, the subclasses of `Illuminate\Database\Connection` aren't stored or referred to as "Adaptors" so would this add confusion? Would the synonym "Driver" be more apt?

File: src/Extracting/Strategies/Strategy.php (hunk 2 above)
Comment (Smudge3806) [reply src/Extracting/Strategies/Strategy.php:32]: Fixed the description. Hopefully it's clearer.

File: config/scribe.php (hunk 1 above)
Comment (Smudge3806) [reply config/scribe.php:345]: On review and consultation, we like `run_without_database_transactions` when in the array form.

File: src/Extracting/DatabaseTransactionHelpers.php (hunk 4 above)
Comment (Smudge3806) [reply src/Extracting/DatabaseTransactionHelpers.php]: I have updated the messaging to..
> Database driver for the connection [mongodb] does not support transactions!

This also maps to the message in the `DbTransactionSupportException` with.. 
> Database driver [Jenssegers\Mongodb\Connection] for connection [mongodb] does not support transactions. Changes to your database will be persistent. To allow this, add "mongodb" to the "run_without_database_transactions" config.

Thoughts?

Comment (shalvah) [reply src/Extracting/DatabaseTransactionHelpers.php]: Yeah, that's good.

**Comment by shalvah** [comment]
Fine with this, so I'm merging. A few minor nitpicks, but I'll add those in myself. Thanks!

File: src/Extracting/DatabaseTransactionHelpers.php (hunk 4 above)
Comment (shalvah) [reply src/Extracting/DatabaseTransactionHelpers.php]: Actually, I'm going to lay the blame on the driver. The connection is an arbitrary name the user picks.

**Comment by shalvah** [comment]
Finally went with `continue_without_database_transactions`as the config name.😅 #57
